#!/bin/bash

LANDO_APP_NAME=$(cat .lando.yml | head -n1 | awk '{ print $2 }')

echo "Adding auth to ssh-agent"
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa

read -p "Is this a multisite? [yes/no]: " MULTISITE

echo "Downloading latest version of WordPress"
curl -O https://wordpress.org/latest.tar.gz
tar -xvf latest.tar.gz
rm latest.tar.gz

echo "Cloning git@github.com:wpcomvip/$LANDO_APP_NAME"
git clone git@github.com:wpcomvip/"$LANDO_APP_NAME"
rsync -avh "$LANDO_APP_NAME"/ wordpress/wp-content
rm -rf "$LANDO_APP_NAME"

echo "Launching server"
lando start

if [[ "yes" == "$MULTISITE" ]]
then
    lando multisite-install
else
    lando wp-install
fi

echo "Cloning VIP Go mu-plugins"
git clone git@github.com:Automattic/vip-go-mu-plugins-built.git
rsync -avh ./vip-go-mu-plugins-built/ wordpress/wp-content/mu-plugins
rm -rf vip-go-mu-plugins-built

echo "Setting Up PhpStorm Config"
.lando/xdebug

echo "Cleaning Up"
rm -rf .git
rm .gitignore
rm Readme.md
rm -rf .lando
rm -- "$0"

echo "All done!"
echo https://"$LANDO_APP_NAME".lndo.site
