#!/bin/bash
cd wordpress

wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --extra-php \
<<PHP
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

/* VIP Go Specific Configuration */

if ( file_exists( __DIR__ . '/wp-content/vip-config/vip-config.php' ) ) {
    require_once( __DIR__ . '/wp-content/vip-config/vip-config.php' );
}

define( 'DISALLOW_FILE_EDIT', true );
define( 'DISALLOW_FILE_MODS', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );
PHP

wp core multisite-install  --url="$LANDO_APP_NAME".lndo.site --title="$LANDO_APP_NAME" --admin_user="$LANDO_APP_NAME" --admin_password="$LANDO_APP_NAME" --admin_email=info@example.com --skip-email
wp theme activate "$LANDO_APP_NAME"